const express = require("express");
const router = express.Router();
const { auth } = require("../middlewares/auth");
const { subDomainChecker } = require("../middlewares/subDomainChecker");

const home = require("./home");
const storeInfo = require("./storeInfo");
const basket = require("./basket");
const productsPage = require("./productsPage");
const productPage = require("./productPage");
const uploadProduct = require("./uploadProduct");
const editProduct = require("./editProduct");
const editProducts = require("./editProducts");
const editHome = require("./editHome");
const deleteProduct = require("./deleteProduct");
const signUp = require("./signUp");
const logIn = require("./logIn");
const dashboard = require("./dashboard");
const search = require("./search");
const customerInfo = require("./customerInfo");
const zarinpal = require("./zarinpal");
const purchase = require("./purchase");
const sort = require("./sort");
const support = require("./support");
const purchasesView = require("./purchasesView");
const settings = require("./settings");

router.use("/", subDomainChecker, home);
router.use("/storeInfo", subDomainChecker, storeInfo);
router.use("/productsPage", subDomainChecker, productsPage);
router.use("/productPage", subDomainChecker, productPage);
router.use("/search", subDomainChecker, search);
router.use("/sort", subDomainChecker, sort);
router.use("/support", subDomainChecker, support);
router.use("/purchase", subDomainChecker, purchase);
router.use("/basket", subDomainChecker, basket);
router.use("/dashboard", auth, dashboard);
router.use("/settings", auth, settings);
router.use("/purchasesView", auth, purchasesView);
router.use("/uploadProduct", auth, uploadProduct);
router.use("/editProduct", auth, editProduct);
router.use("/editProducts", auth, editProducts);
router.use("/editHome", auth, editHome);
router.use("/deleteProduct", auth, deleteProduct);
router.use("/zarinpal", zarinpal);
router.use("/customerInfo", customerInfo);
router.use("/signUp", signUp);
router.use("/logIn", logIn);

module.exports = router;
