const express = require("express");
const router = express.Router();
const { auth } = require("../../middlewares/auth");
const signUp = require("./signUp");
const logIn = require("./logIn");
const changePassword = require("./changePassword");
const dashboard = require("./dashboard");
const settings = require("./settings");
const purchasesView = require("./purchasesView");
const uploadProduct = require("./uploadProduct");
const editProduct = require("./editProduct");
const editProducts = require("./editProducts");
const editCategories = require("./editCategories");
const deleteProduct = require("./deleteProduct");
const uploadCategory = require("./uploadCategory");
const deleteCategory = require("./deleteCategory");
const editCategory = require("./editCategory");
const mergeCategories = require("./mergeCategories");
const banner = require("./banner");

router.use("/signUp", signUp);
router.use("/logIn", logIn);
router.use("/changePassword", auth, changePassword);
router.use("/dashboard", auth, dashboard);
router.use("/settings", auth, settings);
router.use("/purchasesView", auth, purchasesView);
router.use("/uploadProduct", auth, uploadProduct);
router.use("/editProduct", auth, editProduct);
router.use("/editProducts", auth, editProducts);
router.use("/editCategories", auth, editCategories);
router.use("/deleteProduct", auth, deleteProduct);
router.use("/uploadCategory", auth, uploadCategory);
router.use("/deleteCategory", auth, deleteCategory);
router.use("/editCategory", auth, editCategory);
router.use("/mergeCategories", auth, mergeCategories);
router.use("/banner", auth, banner);

module.exports = router;
